#ifndef IOCP_RESOURCE_H_HEADER_INCLUDED_A5CF5EB5
#define IOCP_RESOURCE_H_HEADER_INCLUDED_A5CF5EB5

//##ModelId=5A26051F0071
class iocp_resource
{
};



#endif /* IOCP_RESOURCE_H_HEADER_INCLUDED_A5CF5EB5 */
