#ifndef SOCKETCONTEXT_H_HEADER_INCLUDED_A5CF1AEE
#define SOCKETCONTEXT_H_HEADER_INCLUDED_A5CF1AEE

//##ModelId=5A2639A801AF
class SocketContext
{
};



#endif /* SOCKETCONTEXT_H_HEADER_INCLUDED_A5CF1AEE */
