include(../configuration.pri)
include(../CommonFile/CommonFile.pri)
include(../Model/Model.pri)
include(../View/View.pri)
include(../Controller/Controller.pri)
include(../Component/Component.pri)
include($$QT_3RDPARTYPATH/MLog/MLog.pri)
include($$QT_3RDPARTYPATH/MConfigManage/MConfigManage.pri)
include($$QT_3RDPARTYPATH/MFramelessWidget/MFramelessWidget.pri)
include($$QT_3RDPARTYPATH/ReadWriteExcel/ReadWriteExcel.pri)

