// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef PROTOBUF_Message_2eproto__INCLUDED
#define PROTOBUF_Message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pbmsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Message_2eproto();
void protobuf_AssignDesc_Message_2eproto();
void protobuf_ShutdownFile_Message_2eproto();

class LoginRequest;
class LoginResponse;
class Friend;
class GetFriendsResponse;
class SendMessageRequest;
class FriendNotification;
class MessageNotification;
class WelcomeNotification;
class Request;
class Response;
class Notification;
class Message;

enum MSG {
  Login_Request = 10001,
  Login_Response = 10002,
  Logout_Request = 10003,
  Logout_Response = 10004,
  Keepalive_Request = 10005,
  Keepalive_Response = 10006,
  Get_Friends_Request = 10007,
  Get_Friends_Response = 10008,
  Send_Message_Request = 10009,
  Send_Message_Response = 10010,
  Friend_Notification = 20001,
  Message_Notification = 20002,
  Welcome_Notification = 20003
};
bool MSG_IsValid(int value);
const MSG MSG_MIN = Login_Request;
const MSG MSG_MAX = Welcome_Notification;
const int MSG_ARRAYSIZE = MSG_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSG_descriptor();
inline const ::std::string& MSG_Name(MSG value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSG_descriptor(), value);
}
inline bool MSG_Parse(
    const ::std::string& name, MSG* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSG>(
    MSG_descriptor(), name, value);
}
enum ERR_CODE {
  CLIENT_ERR_REFUSE = 100001,
  CLIENT_ERR_ACCEPT = 100002,
  SERVER1_ERR_STOP = 200001,
  SERVER2_ERR_OVERLOAD = 300001
};
bool ERR_CODE_IsValid(int value);
const ERR_CODE ERR_CODE_MIN = CLIENT_ERR_REFUSE;
const ERR_CODE ERR_CODE_MAX = SERVER2_ERR_OVERLOAD;
const int ERR_CODE_ARRAYSIZE = ERR_CODE_MAX + 1;

const ::google::protobuf::EnumDescriptor* ERR_CODE_descriptor();
inline const ::std::string& ERR_CODE_Name(ERR_CODE value) {
  return ::google::protobuf::internal::NameOfEnum(
    ERR_CODE_descriptor(), value);
}
inline bool ERR_CODE_Parse(
    const ::std::string& name, ERR_CODE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ERR_CODE>(
    ERR_CODE_descriptor(), name, value);
}
// ===================================================================

class LoginRequest : public ::google::protobuf::Message {
 public:
  LoginRequest();
  virtual ~LoginRequest();

  LoginRequest(const LoginRequest& from);

  inline LoginRequest& operator=(const LoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRequest& default_instance();

  void Swap(LoginRequest* other);

  // implements Message ----------------------------------------------

  LoginRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRequest& from);
  void MergeFrom(const LoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes username = 1;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUsernameFieldNumber = 1;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const void* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // optional string password = 2;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 2;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:pbmsg.LoginRequest)
 private:
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_password();
  inline void clear_has_password();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* username_;
  ::std::string* password_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static LoginRequest* default_instance_;
};
// -------------------------------------------------------------------

class LoginResponse : public ::google::protobuf::Message {
 public:
  LoginResponse();
  virtual ~LoginResponse();

  LoginResponse(const LoginResponse& from);

  inline LoginResponse& operator=(const LoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginResponse& default_instance();

  void Swap(LoginResponse* other);

  // implements Message ----------------------------------------------

  LoginResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginResponse& from);
  void MergeFrom(const LoginResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 ttl = 1;
  inline bool has_ttl() const;
  inline void clear_ttl();
  static const int kTtlFieldNumber = 1;
  inline ::google::protobuf::uint32 ttl() const;
  inline void set_ttl(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pbmsg.LoginResponse)
 private:
  inline void set_has_ttl();
  inline void clear_has_ttl();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 ttl_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static LoginResponse* default_instance_;
};
// -------------------------------------------------------------------

class Friend : public ::google::protobuf::Message {
 public:
  Friend();
  virtual ~Friend();

  Friend(const Friend& from);

  inline Friend& operator=(const Friend& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Friend& default_instance();

  void Swap(Friend* other);

  // implements Message ----------------------------------------------

  Friend* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Friend& from);
  void MergeFrom(const Friend& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional bool online = 2;
  inline bool has_online() const;
  inline void clear_online();
  static const int kOnlineFieldNumber = 2;
  inline bool online() const;
  inline void set_online(bool value);

  // @@protoc_insertion_point(class_scope:pbmsg.Friend)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_online();
  inline void clear_has_online();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  bool online_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Friend* default_instance_;
};
// -------------------------------------------------------------------

class GetFriendsResponse : public ::google::protobuf::Message {
 public:
  GetFriendsResponse();
  virtual ~GetFriendsResponse();

  GetFriendsResponse(const GetFriendsResponse& from);

  inline GetFriendsResponse& operator=(const GetFriendsResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetFriendsResponse& default_instance();

  void Swap(GetFriendsResponse* other);

  // implements Message ----------------------------------------------

  GetFriendsResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetFriendsResponse& from);
  void MergeFrom(const GetFriendsResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pbmsg.Friend friends = 1;
  inline int friends_size() const;
  inline void clear_friends();
  static const int kFriendsFieldNumber = 1;
  inline const ::pbmsg::Friend& friends(int index) const;
  inline ::pbmsg::Friend* mutable_friends(int index);
  inline ::pbmsg::Friend* add_friends();
  inline const ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend >&
      friends() const;
  inline ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend >*
      mutable_friends();

  // @@protoc_insertion_point(class_scope:pbmsg.GetFriendsResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend > friends_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static GetFriendsResponse* default_instance_;
};
// -------------------------------------------------------------------

class SendMessageRequest : public ::google::protobuf::Message {
 public:
  SendMessageRequest();
  virtual ~SendMessageRequest();

  SendMessageRequest(const SendMessageRequest& from);

  inline SendMessageRequest& operator=(const SendMessageRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SendMessageRequest& default_instance();

  void Swap(SendMessageRequest* other);

  // implements Message ----------------------------------------------

  SendMessageRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SendMessageRequest& from);
  void MergeFrom(const SendMessageRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes receiver = 1;
  inline bool has_receiver() const;
  inline void clear_receiver();
  static const int kReceiverFieldNumber = 1;
  inline const ::std::string& receiver() const;
  inline void set_receiver(const ::std::string& value);
  inline void set_receiver(const char* value);
  inline void set_receiver(const void* value, size_t size);
  inline ::std::string* mutable_receiver();
  inline ::std::string* release_receiver();
  inline void set_allocated_receiver(::std::string* receiver);

  // required bytes text = 2;
  inline bool has_text() const;
  inline void clear_text();
  static const int kTextFieldNumber = 2;
  inline const ::std::string& text() const;
  inline void set_text(const ::std::string& value);
  inline void set_text(const char* value);
  inline void set_text(const void* value, size_t size);
  inline ::std::string* mutable_text();
  inline ::std::string* release_text();
  inline void set_allocated_text(::std::string* text);

  // @@protoc_insertion_point(class_scope:pbmsg.SendMessageRequest)
 private:
  inline void set_has_receiver();
  inline void clear_has_receiver();
  inline void set_has_text();
  inline void clear_has_text();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* receiver_;
  ::std::string* text_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static SendMessageRequest* default_instance_;
};
// -------------------------------------------------------------------

class FriendNotification : public ::google::protobuf::Message {
 public:
  FriendNotification();
  virtual ~FriendNotification();

  FriendNotification(const FriendNotification& from);

  inline FriendNotification& operator=(const FriendNotification& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FriendNotification& default_instance();

  void Swap(FriendNotification* other);

  // implements Message ----------------------------------------------

  FriendNotification* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FriendNotification& from);
  void MergeFrom(const FriendNotification& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional bool online = 2;
  inline bool has_online() const;
  inline void clear_online();
  static const int kOnlineFieldNumber = 2;
  inline bool online() const;
  inline void set_online(bool value);

  // @@protoc_insertion_point(class_scope:pbmsg.FriendNotification)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_online();
  inline void clear_has_online();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  bool online_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static FriendNotification* default_instance_;
};
// -------------------------------------------------------------------

class MessageNotification : public ::google::protobuf::Message {
 public:
  MessageNotification();
  virtual ~MessageNotification();

  MessageNotification(const MessageNotification& from);

  inline MessageNotification& operator=(const MessageNotification& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageNotification& default_instance();

  void Swap(MessageNotification* other);

  // implements Message ----------------------------------------------

  MessageNotification* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageNotification& from);
  void MergeFrom(const MessageNotification& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes sender = 1;
  inline bool has_sender() const;
  inline void clear_sender();
  static const int kSenderFieldNumber = 1;
  inline const ::std::string& sender() const;
  inline void set_sender(const ::std::string& value);
  inline void set_sender(const char* value);
  inline void set_sender(const void* value, size_t size);
  inline ::std::string* mutable_sender();
  inline ::std::string* release_sender();
  inline void set_allocated_sender(::std::string* sender);

  // required bytes text = 2;
  inline bool has_text() const;
  inline void clear_text();
  static const int kTextFieldNumber = 2;
  inline const ::std::string& text() const;
  inline void set_text(const ::std::string& value);
  inline void set_text(const char* value);
  inline void set_text(const void* value, size_t size);
  inline ::std::string* mutable_text();
  inline ::std::string* release_text();
  inline void set_allocated_text(::std::string* text);

  // required string timestamp = 3;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  inline const ::std::string& timestamp() const;
  inline void set_timestamp(const ::std::string& value);
  inline void set_timestamp(const char* value);
  inline void set_timestamp(const char* value, size_t size);
  inline ::std::string* mutable_timestamp();
  inline ::std::string* release_timestamp();
  inline void set_allocated_timestamp(::std::string* timestamp);

  // @@protoc_insertion_point(class_scope:pbmsg.MessageNotification)
 private:
  inline void set_has_sender();
  inline void clear_has_sender();
  inline void set_has_text();
  inline void clear_has_text();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* sender_;
  ::std::string* text_;
  ::std::string* timestamp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static MessageNotification* default_instance_;
};
// -------------------------------------------------------------------

class WelcomeNotification : public ::google::protobuf::Message {
 public:
  WelcomeNotification();
  virtual ~WelcomeNotification();

  WelcomeNotification(const WelcomeNotification& from);

  inline WelcomeNotification& operator=(const WelcomeNotification& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WelcomeNotification& default_instance();

  void Swap(WelcomeNotification* other);

  // implements Message ----------------------------------------------

  WelcomeNotification* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WelcomeNotification& from);
  void MergeFrom(const WelcomeNotification& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes text = 1;
  inline bool has_text() const;
  inline void clear_text();
  static const int kTextFieldNumber = 1;
  inline const ::std::string& text() const;
  inline void set_text(const ::std::string& value);
  inline void set_text(const char* value);
  inline void set_text(const void* value, size_t size);
  inline ::std::string* mutable_text();
  inline ::std::string* release_text();
  inline void set_allocated_text(::std::string* text);

  // @@protoc_insertion_point(class_scope:pbmsg.WelcomeNotification)
 private:
  inline void set_has_text();
  inline void clear_has_text();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* text_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static WelcomeNotification* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .pbmsg.LoginRequest login = 1;
  inline bool has_login() const;
  inline void clear_login();
  static const int kLoginFieldNumber = 1;
  inline const ::pbmsg::LoginRequest& login() const;
  inline ::pbmsg::LoginRequest* mutable_login();
  inline ::pbmsg::LoginRequest* release_login();
  inline void set_allocated_login(::pbmsg::LoginRequest* login);

  // optional .pbmsg.SendMessageRequest send_message = 2;
  inline bool has_send_message() const;
  inline void clear_send_message();
  static const int kSendMessageFieldNumber = 2;
  inline const ::pbmsg::SendMessageRequest& send_message() const;
  inline ::pbmsg::SendMessageRequest* mutable_send_message();
  inline ::pbmsg::SendMessageRequest* release_send_message();
  inline void set_allocated_send_message(::pbmsg::SendMessageRequest* send_message);

  // @@protoc_insertion_point(class_scope:pbmsg.Request)
 private:
  inline void set_has_login();
  inline void clear_has_login();
  inline void set_has_send_message();
  inline void clear_has_send_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::pbmsg::LoginRequest* login_;
  ::pbmsg::SendMessageRequest* send_message_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void Swap(Response* other);

  // implements Message ----------------------------------------------

  Response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline bool result() const;
  inline void set_result(bool value);

  // required bool last_response = 2;
  inline bool has_last_response() const;
  inline void clear_last_response();
  static const int kLastResponseFieldNumber = 2;
  inline bool last_response() const;
  inline void set_last_response(bool value);

  // optional bytes error_describe = 3;
  inline bool has_error_describe() const;
  inline void clear_error_describe();
  static const int kErrorDescribeFieldNumber = 3;
  inline const ::std::string& error_describe() const;
  inline void set_error_describe(const ::std::string& value);
  inline void set_error_describe(const char* value);
  inline void set_error_describe(const void* value, size_t size);
  inline ::std::string* mutable_error_describe();
  inline ::std::string* release_error_describe();
  inline void set_allocated_error_describe(::std::string* error_describe);

  // optional .pbmsg.LoginResponse login = 4;
  inline bool has_login() const;
  inline void clear_login();
  static const int kLoginFieldNumber = 4;
  inline const ::pbmsg::LoginResponse& login() const;
  inline ::pbmsg::LoginResponse* mutable_login();
  inline ::pbmsg::LoginResponse* release_login();
  inline void set_allocated_login(::pbmsg::LoginResponse* login);

  // optional .pbmsg.GetFriendsResponse get_friends = 5;
  inline bool has_get_friends() const;
  inline void clear_get_friends();
  static const int kGetFriendsFieldNumber = 5;
  inline const ::pbmsg::GetFriendsResponse& get_friends() const;
  inline ::pbmsg::GetFriendsResponse* mutable_get_friends();
  inline ::pbmsg::GetFriendsResponse* release_get_friends();
  inline void set_allocated_get_friends(::pbmsg::GetFriendsResponse* get_friends);

  // @@protoc_insertion_point(class_scope:pbmsg.Response)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_last_response();
  inline void clear_has_last_response();
  inline void set_has_error_describe();
  inline void clear_has_error_describe();
  inline void set_has_login();
  inline void clear_has_login();
  inline void set_has_get_friends();
  inline void clear_has_get_friends();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* error_describe_;
  ::pbmsg::LoginResponse* login_;
  ::pbmsg::GetFriendsResponse* get_friends_;
  bool result_;
  bool last_response_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// -------------------------------------------------------------------

class Notification : public ::google::protobuf::Message {
 public:
  Notification();
  virtual ~Notification();

  Notification(const Notification& from);

  inline Notification& operator=(const Notification& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Notification& default_instance();

  void Swap(Notification* other);

  // implements Message ----------------------------------------------

  Notification* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Notification& from);
  void MergeFrom(const Notification& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .pbmsg.FriendNotification friend = 1;
  inline bool has_friend_() const;
  inline void clear_friend_();
  static const int kFriendFieldNumber = 1;
  inline const ::pbmsg::FriendNotification& friend_() const;
  inline ::pbmsg::FriendNotification* mutable_friend_();
  inline ::pbmsg::FriendNotification* release_friend_();
  inline void set_allocated_friend_(::pbmsg::FriendNotification* friend_);

  // optional .pbmsg.MessageNotification msg = 2;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 2;
  inline const ::pbmsg::MessageNotification& msg() const;
  inline ::pbmsg::MessageNotification* mutable_msg();
  inline ::pbmsg::MessageNotification* release_msg();
  inline void set_allocated_msg(::pbmsg::MessageNotification* msg);

  // optional .pbmsg.WelcomeNotification welcome = 3;
  inline bool has_welcome() const;
  inline void clear_welcome();
  static const int kWelcomeFieldNumber = 3;
  inline const ::pbmsg::WelcomeNotification& welcome() const;
  inline ::pbmsg::WelcomeNotification* mutable_welcome();
  inline ::pbmsg::WelcomeNotification* release_welcome();
  inline void set_allocated_welcome(::pbmsg::WelcomeNotification* welcome);

  // @@protoc_insertion_point(class_scope:pbmsg.Notification)
 private:
  inline void set_has_friend_();
  inline void clear_has_friend_();
  inline void set_has_msg();
  inline void clear_has_msg();
  inline void set_has_welcome();
  inline void clear_has_welcome();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::pbmsg::FriendNotification* friend__;
  ::pbmsg::MessageNotification* msg_;
  ::pbmsg::WelcomeNotification* welcome_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Notification* default_instance_;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  Message* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .pbmsg.MSG msg_type = 1;
  inline bool has_msg_type() const;
  inline void clear_msg_type();
  static const int kMsgTypeFieldNumber = 1;
  inline ::pbmsg::MSG msg_type() const;
  inline void set_msg_type(::pbmsg::MSG value);

  // required fixed32 sequence = 2;
  inline bool has_sequence() const;
  inline void clear_sequence();
  static const int kSequenceFieldNumber = 2;
  inline ::google::protobuf::uint32 sequence() const;
  inline void set_sequence(::google::protobuf::uint32 value);

  // optional fixed32 session_id = 3;
  inline bool has_session_id() const;
  inline void clear_session_id();
  static const int kSessionIdFieldNumber = 3;
  inline ::google::protobuf::uint32 session_id() const;
  inline void set_session_id(::google::protobuf::uint32 value);

  // optional .pbmsg.Request request = 4;
  inline bool has_request() const;
  inline void clear_request();
  static const int kRequestFieldNumber = 4;
  inline const ::pbmsg::Request& request() const;
  inline ::pbmsg::Request* mutable_request();
  inline ::pbmsg::Request* release_request();
  inline void set_allocated_request(::pbmsg::Request* request);

  // optional .pbmsg.Response response = 5;
  inline bool has_response() const;
  inline void clear_response();
  static const int kResponseFieldNumber = 5;
  inline const ::pbmsg::Response& response() const;
  inline ::pbmsg::Response* mutable_response();
  inline ::pbmsg::Response* release_response();
  inline void set_allocated_response(::pbmsg::Response* response);

  // optional .pbmsg.Notification notification = 6;
  inline bool has_notification() const;
  inline void clear_notification();
  static const int kNotificationFieldNumber = 6;
  inline const ::pbmsg::Notification& notification() const;
  inline ::pbmsg::Notification* mutable_notification();
  inline ::pbmsg::Notification* release_notification();
  inline void set_allocated_notification(::pbmsg::Notification* notification);

  // @@protoc_insertion_point(class_scope:pbmsg.Message)
 private:
  inline void set_has_msg_type();
  inline void clear_has_msg_type();
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_session_id();
  inline void clear_has_session_id();
  inline void set_has_request();
  inline void clear_has_request();
  inline void set_has_response();
  inline void clear_has_response();
  inline void set_has_notification();
  inline void clear_has_notification();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int msg_type_;
  ::google::protobuf::uint32 sequence_;
  ::pbmsg::Request* request_;
  ::pbmsg::Response* response_;
  ::pbmsg::Notification* notification_;
  ::google::protobuf::uint32 session_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Message* default_instance_;
};
// ===================================================================


// ===================================================================

// LoginRequest

// required bytes username = 1;
inline bool LoginRequest::has_username() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRequest::set_has_username() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRequest::clear_has_username() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRequest::clear_username() {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& LoginRequest::username() const {
  return *username_;
}
inline void LoginRequest::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void LoginRequest::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void LoginRequest::set_username(const void* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LoginRequest::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  return username_;
}
inline ::std::string* LoginRequest::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LoginRequest::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string password = 2;
inline bool LoginRequest::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginRequest::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginRequest::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginRequest::clear_password() {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& LoginRequest::password() const {
  return *password_;
}
inline void LoginRequest::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void LoginRequest::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void LoginRequest::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LoginRequest::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  return password_;
}
inline ::std::string* LoginRequest::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LoginRequest::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// LoginResponse

// required fixed32 ttl = 1;
inline bool LoginResponse::has_ttl() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginResponse::set_has_ttl() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginResponse::clear_has_ttl() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginResponse::clear_ttl() {
  ttl_ = 0u;
  clear_has_ttl();
}
inline ::google::protobuf::uint32 LoginResponse::ttl() const {
  return ttl_;
}
inline void LoginResponse::set_ttl(::google::protobuf::uint32 value) {
  set_has_ttl();
  ttl_ = value;
}

// -------------------------------------------------------------------

// Friend

// required bytes name = 1;
inline bool Friend::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Friend::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Friend::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Friend::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Friend::name() const {
  return *name_;
}
inline void Friend::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Friend::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Friend::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Friend::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Friend::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Friend::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool online = 2;
inline bool Friend::has_online() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Friend::set_has_online() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Friend::clear_has_online() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Friend::clear_online() {
  online_ = false;
  clear_has_online();
}
inline bool Friend::online() const {
  return online_;
}
inline void Friend::set_online(bool value) {
  set_has_online();
  online_ = value;
}

// -------------------------------------------------------------------

// GetFriendsResponse

// repeated .pbmsg.Friend friends = 1;
inline int GetFriendsResponse::friends_size() const {
  return friends_.size();
}
inline void GetFriendsResponse::clear_friends() {
  friends_.Clear();
}
inline const ::pbmsg::Friend& GetFriendsResponse::friends(int index) const {
  return friends_.Get(index);
}
inline ::pbmsg::Friend* GetFriendsResponse::mutable_friends(int index) {
  return friends_.Mutable(index);
}
inline ::pbmsg::Friend* GetFriendsResponse::add_friends() {
  return friends_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend >&
GetFriendsResponse::friends() const {
  return friends_;
}
inline ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend >*
GetFriendsResponse::mutable_friends() {
  return &friends_;
}

// -------------------------------------------------------------------

// SendMessageRequest

// optional bytes receiver = 1;
inline bool SendMessageRequest::has_receiver() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SendMessageRequest::set_has_receiver() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SendMessageRequest::clear_has_receiver() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SendMessageRequest::clear_receiver() {
  if (receiver_ != &::google::protobuf::internal::kEmptyString) {
    receiver_->clear();
  }
  clear_has_receiver();
}
inline const ::std::string& SendMessageRequest::receiver() const {
  return *receiver_;
}
inline void SendMessageRequest::set_receiver(const ::std::string& value) {
  set_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    receiver_ = new ::std::string;
  }
  receiver_->assign(value);
}
inline void SendMessageRequest::set_receiver(const char* value) {
  set_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    receiver_ = new ::std::string;
  }
  receiver_->assign(value);
}
inline void SendMessageRequest::set_receiver(const void* value, size_t size) {
  set_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    receiver_ = new ::std::string;
  }
  receiver_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SendMessageRequest::mutable_receiver() {
  set_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    receiver_ = new ::std::string;
  }
  return receiver_;
}
inline ::std::string* SendMessageRequest::release_receiver() {
  clear_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = receiver_;
    receiver_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SendMessageRequest::set_allocated_receiver(::std::string* receiver) {
  if (receiver_ != &::google::protobuf::internal::kEmptyString) {
    delete receiver_;
  }
  if (receiver) {
    set_has_receiver();
    receiver_ = receiver;
  } else {
    clear_has_receiver();
    receiver_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes text = 2;
inline bool SendMessageRequest::has_text() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SendMessageRequest::set_has_text() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SendMessageRequest::clear_has_text() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SendMessageRequest::clear_text() {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    text_->clear();
  }
  clear_has_text();
}
inline const ::std::string& SendMessageRequest::text() const {
  return *text_;
}
inline void SendMessageRequest::set_text(const ::std::string& value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void SendMessageRequest::set_text(const char* value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void SendMessageRequest::set_text(const void* value, size_t size) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SendMessageRequest::mutable_text() {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  return text_;
}
inline ::std::string* SendMessageRequest::release_text() {
  clear_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = text_;
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SendMessageRequest::set_allocated_text(::std::string* text) {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    delete text_;
  }
  if (text) {
    set_has_text();
    text_ = text;
  } else {
    clear_has_text();
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// FriendNotification

// required bytes name = 1;
inline bool FriendNotification::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FriendNotification::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FriendNotification::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FriendNotification::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& FriendNotification::name() const {
  return *name_;
}
inline void FriendNotification::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void FriendNotification::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void FriendNotification::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FriendNotification::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* FriendNotification::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void FriendNotification::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool online = 2;
inline bool FriendNotification::has_online() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FriendNotification::set_has_online() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FriendNotification::clear_has_online() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FriendNotification::clear_online() {
  online_ = false;
  clear_has_online();
}
inline bool FriendNotification::online() const {
  return online_;
}
inline void FriendNotification::set_online(bool value) {
  set_has_online();
  online_ = value;
}

// -------------------------------------------------------------------

// MessageNotification

// required bytes sender = 1;
inline bool MessageNotification::has_sender() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageNotification::set_has_sender() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageNotification::clear_has_sender() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageNotification::clear_sender() {
  if (sender_ != &::google::protobuf::internal::kEmptyString) {
    sender_->clear();
  }
  clear_has_sender();
}
inline const ::std::string& MessageNotification::sender() const {
  return *sender_;
}
inline void MessageNotification::set_sender(const ::std::string& value) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
}
inline void MessageNotification::set_sender(const char* value) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
}
inline void MessageNotification::set_sender(const void* value, size_t size) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MessageNotification::mutable_sender() {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  return sender_;
}
inline ::std::string* MessageNotification::release_sender() {
  clear_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sender_;
    sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MessageNotification::set_allocated_sender(::std::string* sender) {
  if (sender_ != &::google::protobuf::internal::kEmptyString) {
    delete sender_;
  }
  if (sender) {
    set_has_sender();
    sender_ = sender;
  } else {
    clear_has_sender();
    sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes text = 2;
inline bool MessageNotification::has_text() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageNotification::set_has_text() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageNotification::clear_has_text() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageNotification::clear_text() {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    text_->clear();
  }
  clear_has_text();
}
inline const ::std::string& MessageNotification::text() const {
  return *text_;
}
inline void MessageNotification::set_text(const ::std::string& value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void MessageNotification::set_text(const char* value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void MessageNotification::set_text(const void* value, size_t size) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MessageNotification::mutable_text() {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  return text_;
}
inline ::std::string* MessageNotification::release_text() {
  clear_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = text_;
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MessageNotification::set_allocated_text(::std::string* text) {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    delete text_;
  }
  if (text) {
    set_has_text();
    text_ = text;
  } else {
    clear_has_text();
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string timestamp = 3;
inline bool MessageNotification::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageNotification::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageNotification::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageNotification::clear_timestamp() {
  if (timestamp_ != &::google::protobuf::internal::kEmptyString) {
    timestamp_->clear();
  }
  clear_has_timestamp();
}
inline const ::std::string& MessageNotification::timestamp() const {
  return *timestamp_;
}
inline void MessageNotification::set_timestamp(const ::std::string& value) {
  set_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    timestamp_ = new ::std::string;
  }
  timestamp_->assign(value);
}
inline void MessageNotification::set_timestamp(const char* value) {
  set_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    timestamp_ = new ::std::string;
  }
  timestamp_->assign(value);
}
inline void MessageNotification::set_timestamp(const char* value, size_t size) {
  set_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    timestamp_ = new ::std::string;
  }
  timestamp_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MessageNotification::mutable_timestamp() {
  set_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    timestamp_ = new ::std::string;
  }
  return timestamp_;
}
inline ::std::string* MessageNotification::release_timestamp() {
  clear_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = timestamp_;
    timestamp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MessageNotification::set_allocated_timestamp(::std::string* timestamp) {
  if (timestamp_ != &::google::protobuf::internal::kEmptyString) {
    delete timestamp_;
  }
  if (timestamp) {
    set_has_timestamp();
    timestamp_ = timestamp;
  } else {
    clear_has_timestamp();
    timestamp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// WelcomeNotification

// required bytes text = 1;
inline bool WelcomeNotification::has_text() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WelcomeNotification::set_has_text() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WelcomeNotification::clear_has_text() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WelcomeNotification::clear_text() {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    text_->clear();
  }
  clear_has_text();
}
inline const ::std::string& WelcomeNotification::text() const {
  return *text_;
}
inline void WelcomeNotification::set_text(const ::std::string& value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void WelcomeNotification::set_text(const char* value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void WelcomeNotification::set_text(const void* value, size_t size) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* WelcomeNotification::mutable_text() {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  return text_;
}
inline ::std::string* WelcomeNotification::release_text() {
  clear_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = text_;
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void WelcomeNotification::set_allocated_text(::std::string* text) {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    delete text_;
  }
  if (text) {
    set_has_text();
    text_ = text;
  } else {
    clear_has_text();
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Request

// optional .pbmsg.LoginRequest login = 1;
inline bool Request::has_login() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_login() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_login() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_login() {
  if (login_ != NULL) login_->::pbmsg::LoginRequest::Clear();
  clear_has_login();
}
inline const ::pbmsg::LoginRequest& Request::login() const {
  return login_ != NULL ? *login_ : *default_instance_->login_;
}
inline ::pbmsg::LoginRequest* Request::mutable_login() {
  set_has_login();
  if (login_ == NULL) login_ = new ::pbmsg::LoginRequest;
  return login_;
}
inline ::pbmsg::LoginRequest* Request::release_login() {
  clear_has_login();
  ::pbmsg::LoginRequest* temp = login_;
  login_ = NULL;
  return temp;
}
inline void Request::set_allocated_login(::pbmsg::LoginRequest* login) {
  delete login_;
  login_ = login;
  if (login) {
    set_has_login();
  } else {
    clear_has_login();
  }
}

// optional .pbmsg.SendMessageRequest send_message = 2;
inline bool Request::has_send_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_send_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_send_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_send_message() {
  if (send_message_ != NULL) send_message_->::pbmsg::SendMessageRequest::Clear();
  clear_has_send_message();
}
inline const ::pbmsg::SendMessageRequest& Request::send_message() const {
  return send_message_ != NULL ? *send_message_ : *default_instance_->send_message_;
}
inline ::pbmsg::SendMessageRequest* Request::mutable_send_message() {
  set_has_send_message();
  if (send_message_ == NULL) send_message_ = new ::pbmsg::SendMessageRequest;
  return send_message_;
}
inline ::pbmsg::SendMessageRequest* Request::release_send_message() {
  clear_has_send_message();
  ::pbmsg::SendMessageRequest* temp = send_message_;
  send_message_ = NULL;
  return temp;
}
inline void Request::set_allocated_send_message(::pbmsg::SendMessageRequest* send_message) {
  delete send_message_;
  send_message_ = send_message;
  if (send_message) {
    set_has_send_message();
  } else {
    clear_has_send_message();
  }
}

// -------------------------------------------------------------------

// Response

// required bool result = 1;
inline bool Response::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_result() {
  result_ = false;
  clear_has_result();
}
inline bool Response::result() const {
  return result_;
}
inline void Response::set_result(bool value) {
  set_has_result();
  result_ = value;
}

// required bool last_response = 2;
inline bool Response::has_last_response() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_last_response() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_last_response() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_last_response() {
  last_response_ = false;
  clear_has_last_response();
}
inline bool Response::last_response() const {
  return last_response_;
}
inline void Response::set_last_response(bool value) {
  set_has_last_response();
  last_response_ = value;
}

// optional bytes error_describe = 3;
inline bool Response::has_error_describe() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_error_describe() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_error_describe() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_error_describe() {
  if (error_describe_ != &::google::protobuf::internal::kEmptyString) {
    error_describe_->clear();
  }
  clear_has_error_describe();
}
inline const ::std::string& Response::error_describe() const {
  return *error_describe_;
}
inline void Response::set_error_describe(const ::std::string& value) {
  set_has_error_describe();
  if (error_describe_ == &::google::protobuf::internal::kEmptyString) {
    error_describe_ = new ::std::string;
  }
  error_describe_->assign(value);
}
inline void Response::set_error_describe(const char* value) {
  set_has_error_describe();
  if (error_describe_ == &::google::protobuf::internal::kEmptyString) {
    error_describe_ = new ::std::string;
  }
  error_describe_->assign(value);
}
inline void Response::set_error_describe(const void* value, size_t size) {
  set_has_error_describe();
  if (error_describe_ == &::google::protobuf::internal::kEmptyString) {
    error_describe_ = new ::std::string;
  }
  error_describe_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Response::mutable_error_describe() {
  set_has_error_describe();
  if (error_describe_ == &::google::protobuf::internal::kEmptyString) {
    error_describe_ = new ::std::string;
  }
  return error_describe_;
}
inline ::std::string* Response::release_error_describe() {
  clear_has_error_describe();
  if (error_describe_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = error_describe_;
    error_describe_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Response::set_allocated_error_describe(::std::string* error_describe) {
  if (error_describe_ != &::google::protobuf::internal::kEmptyString) {
    delete error_describe_;
  }
  if (error_describe) {
    set_has_error_describe();
    error_describe_ = error_describe;
  } else {
    clear_has_error_describe();
    error_describe_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .pbmsg.LoginResponse login = 4;
inline bool Response::has_login() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response::set_has_login() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response::clear_has_login() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response::clear_login() {
  if (login_ != NULL) login_->::pbmsg::LoginResponse::Clear();
  clear_has_login();
}
inline const ::pbmsg::LoginResponse& Response::login() const {
  return login_ != NULL ? *login_ : *default_instance_->login_;
}
inline ::pbmsg::LoginResponse* Response::mutable_login() {
  set_has_login();
  if (login_ == NULL) login_ = new ::pbmsg::LoginResponse;
  return login_;
}
inline ::pbmsg::LoginResponse* Response::release_login() {
  clear_has_login();
  ::pbmsg::LoginResponse* temp = login_;
  login_ = NULL;
  return temp;
}
inline void Response::set_allocated_login(::pbmsg::LoginResponse* login) {
  delete login_;
  login_ = login;
  if (login) {
    set_has_login();
  } else {
    clear_has_login();
  }
}

// optional .pbmsg.GetFriendsResponse get_friends = 5;
inline bool Response::has_get_friends() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Response::set_has_get_friends() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Response::clear_has_get_friends() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Response::clear_get_friends() {
  if (get_friends_ != NULL) get_friends_->::pbmsg::GetFriendsResponse::Clear();
  clear_has_get_friends();
}
inline const ::pbmsg::GetFriendsResponse& Response::get_friends() const {
  return get_friends_ != NULL ? *get_friends_ : *default_instance_->get_friends_;
}
inline ::pbmsg::GetFriendsResponse* Response::mutable_get_friends() {
  set_has_get_friends();
  if (get_friends_ == NULL) get_friends_ = new ::pbmsg::GetFriendsResponse;
  return get_friends_;
}
inline ::pbmsg::GetFriendsResponse* Response::release_get_friends() {
  clear_has_get_friends();
  ::pbmsg::GetFriendsResponse* temp = get_friends_;
  get_friends_ = NULL;
  return temp;
}
inline void Response::set_allocated_get_friends(::pbmsg::GetFriendsResponse* get_friends) {
  delete get_friends_;
  get_friends_ = get_friends;
  if (get_friends) {
    set_has_get_friends();
  } else {
    clear_has_get_friends();
  }
}

// -------------------------------------------------------------------

// Notification

// optional .pbmsg.FriendNotification friend = 1;
inline bool Notification::has_friend_() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Notification::set_has_friend_() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Notification::clear_has_friend_() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Notification::clear_friend_() {
  if (friend__ != NULL) friend__->::pbmsg::FriendNotification::Clear();
  clear_has_friend_();
}
inline const ::pbmsg::FriendNotification& Notification::friend_() const {
  return friend__ != NULL ? *friend__ : *default_instance_->friend__;
}
inline ::pbmsg::FriendNotification* Notification::mutable_friend_() {
  set_has_friend_();
  if (friend__ == NULL) friend__ = new ::pbmsg::FriendNotification;
  return friend__;
}
inline ::pbmsg::FriendNotification* Notification::release_friend_() {
  clear_has_friend_();
  ::pbmsg::FriendNotification* temp = friend__;
  friend__ = NULL;
  return temp;
}
inline void Notification::set_allocated_friend_(::pbmsg::FriendNotification* friend_) {
  delete friend__;
  friend__ = friend_;
  if (friend_) {
    set_has_friend_();
  } else {
    clear_has_friend_();
  }
}

// optional .pbmsg.MessageNotification msg = 2;
inline bool Notification::has_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Notification::set_has_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Notification::clear_has_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Notification::clear_msg() {
  if (msg_ != NULL) msg_->::pbmsg::MessageNotification::Clear();
  clear_has_msg();
}
inline const ::pbmsg::MessageNotification& Notification::msg() const {
  return msg_ != NULL ? *msg_ : *default_instance_->msg_;
}
inline ::pbmsg::MessageNotification* Notification::mutable_msg() {
  set_has_msg();
  if (msg_ == NULL) msg_ = new ::pbmsg::MessageNotification;
  return msg_;
}
inline ::pbmsg::MessageNotification* Notification::release_msg() {
  clear_has_msg();
  ::pbmsg::MessageNotification* temp = msg_;
  msg_ = NULL;
  return temp;
}
inline void Notification::set_allocated_msg(::pbmsg::MessageNotification* msg) {
  delete msg_;
  msg_ = msg;
  if (msg) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
}

// optional .pbmsg.WelcomeNotification welcome = 3;
inline bool Notification::has_welcome() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Notification::set_has_welcome() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Notification::clear_has_welcome() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Notification::clear_welcome() {
  if (welcome_ != NULL) welcome_->::pbmsg::WelcomeNotification::Clear();
  clear_has_welcome();
}
inline const ::pbmsg::WelcomeNotification& Notification::welcome() const {
  return welcome_ != NULL ? *welcome_ : *default_instance_->welcome_;
}
inline ::pbmsg::WelcomeNotification* Notification::mutable_welcome() {
  set_has_welcome();
  if (welcome_ == NULL) welcome_ = new ::pbmsg::WelcomeNotification;
  return welcome_;
}
inline ::pbmsg::WelcomeNotification* Notification::release_welcome() {
  clear_has_welcome();
  ::pbmsg::WelcomeNotification* temp = welcome_;
  welcome_ = NULL;
  return temp;
}
inline void Notification::set_allocated_welcome(::pbmsg::WelcomeNotification* welcome) {
  delete welcome_;
  welcome_ = welcome;
  if (welcome) {
    set_has_welcome();
  } else {
    clear_has_welcome();
  }
}

// -------------------------------------------------------------------

// Message

// required .pbmsg.MSG msg_type = 1;
inline bool Message::has_msg_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_msg_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_msg_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_msg_type() {
  msg_type_ = 10001;
  clear_has_msg_type();
}
inline ::pbmsg::MSG Message::msg_type() const {
  return static_cast< ::pbmsg::MSG >(msg_type_);
}
inline void Message::set_msg_type(::pbmsg::MSG value) {
  assert(::pbmsg::MSG_IsValid(value));
  set_has_msg_type();
  msg_type_ = value;
}

// required fixed32 sequence = 2;
inline bool Message::has_sequence() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_sequence() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_sequence() {
  sequence_ = 0u;
  clear_has_sequence();
}
inline ::google::protobuf::uint32 Message::sequence() const {
  return sequence_;
}
inline void Message::set_sequence(::google::protobuf::uint32 value) {
  set_has_sequence();
  sequence_ = value;
}

// optional fixed32 session_id = 3;
inline bool Message::has_session_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_session_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_session_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_session_id() {
  session_id_ = 0u;
  clear_has_session_id();
}
inline ::google::protobuf::uint32 Message::session_id() const {
  return session_id_;
}
inline void Message::set_session_id(::google::protobuf::uint32 value) {
  set_has_session_id();
  session_id_ = value;
}

// optional .pbmsg.Request request = 4;
inline bool Message::has_request() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_request() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_request() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_request() {
  if (request_ != NULL) request_->::pbmsg::Request::Clear();
  clear_has_request();
}
inline const ::pbmsg::Request& Message::request() const {
  return request_ != NULL ? *request_ : *default_instance_->request_;
}
inline ::pbmsg::Request* Message::mutable_request() {
  set_has_request();
  if (request_ == NULL) request_ = new ::pbmsg::Request;
  return request_;
}
inline ::pbmsg::Request* Message::release_request() {
  clear_has_request();
  ::pbmsg::Request* temp = request_;
  request_ = NULL;
  return temp;
}
inline void Message::set_allocated_request(::pbmsg::Request* request) {
  delete request_;
  request_ = request;
  if (request) {
    set_has_request();
  } else {
    clear_has_request();
  }
}

// optional .pbmsg.Response response = 5;
inline bool Message::has_response() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_response() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_response() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_response() {
  if (response_ != NULL) response_->::pbmsg::Response::Clear();
  clear_has_response();
}
inline const ::pbmsg::Response& Message::response() const {
  return response_ != NULL ? *response_ : *default_instance_->response_;
}
inline ::pbmsg::Response* Message::mutable_response() {
  set_has_response();
  if (response_ == NULL) response_ = new ::pbmsg::Response;
  return response_;
}
inline ::pbmsg::Response* Message::release_response() {
  clear_has_response();
  ::pbmsg::Response* temp = response_;
  response_ = NULL;
  return temp;
}
inline void Message::set_allocated_response(::pbmsg::Response* response) {
  delete response_;
  response_ = response;
  if (response) {
    set_has_response();
  } else {
    clear_has_response();
  }
}

// optional .pbmsg.Notification notification = 6;
inline bool Message::has_notification() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Message::set_has_notification() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Message::clear_has_notification() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Message::clear_notification() {
  if (notification_ != NULL) notification_->::pbmsg::Notification::Clear();
  clear_has_notification();
}
inline const ::pbmsg::Notification& Message::notification() const {
  return notification_ != NULL ? *notification_ : *default_instance_->notification_;
}
inline ::pbmsg::Notification* Message::mutable_notification() {
  set_has_notification();
  if (notification_ == NULL) notification_ = new ::pbmsg::Notification;
  return notification_;
}
inline ::pbmsg::Notification* Message::release_notification() {
  clear_has_notification();
  ::pbmsg::Notification* temp = notification_;
  notification_ = NULL;
  return temp;
}
inline void Message::set_allocated_notification(::pbmsg::Notification* notification) {
  delete notification_;
  notification_ = notification;
  if (notification) {
    set_has_notification();
  } else {
    clear_has_notification();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pbmsg

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pbmsg::MSG>() {
  return ::pbmsg::MSG_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pbmsg::ERR_CODE>() {
  return ::pbmsg::ERR_CODE_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Message_2eproto__INCLUDED
