// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef PROTOBUF_Message_2eproto__INCLUDED
#define PROTOBUF_Message_2eproto__INCLUDED
#include "..\..\..\Framework\include\CommonDefine.h"
#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pbmsg {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Message_2eproto();
void protobuf_AssignDesc_Message_2eproto();
void protobuf_ShutdownFile_Message_2eproto();

class Friend;
class FriendNotify;
class GetFriendsRespond;
class LoginRequest;
class LoginRespond;
class Message;
class MessageNotify;
class Notify;
class Request;
class Respond;
class SendMessageRequest;
class WelcomeNotify;

enum MSG {
  ELoginRequest = 10001,
  ELoginRespond = 10002,
  ELogoutRequest = 10003,
  ELogoutRespond = 10004,
  EKeepaliveRequest = 10005,
  EKeepaliveRespond = 10006,
  EGetFriendsRequest = 10007,
  EGetFriendsRespond = 10008,
  ESendMessageRequest = 10009,
  ESendMessageRespond = 10010,
  EFriendNotify = 20001,
  EMessageNotify = 20002,
  EWelcomeNotify = 20003
};
bool MSG_IsValid(int value);
const MSG MSG_MIN = ELoginRequest;
const MSG MSG_MAX = EWelcomeNotify;
const int MSG_ARRAYSIZE = MSG_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSG_descriptor();
inline const ::std::string& MSG_Name(MSG value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSG_descriptor(), value);
}
inline bool MSG_Parse(
    const ::std::string& name, MSG* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSG>(
    MSG_descriptor(), name, value);
}
enum ERR_CODE {
  CLIENT_ERR_REFUSE = 100001,
  CLIENT_ERR_ACCEPT = 100002,
  SERVER1_ERR_STOP = 200001,
  SERVER2_ERR_OVERLOAD = 300001
};
bool ERR_CODE_IsValid(int value);
const ERR_CODE ERR_CODE_MIN = CLIENT_ERR_REFUSE;
const ERR_CODE ERR_CODE_MAX = SERVER2_ERR_OVERLOAD;
const int ERR_CODE_ARRAYSIZE = ERR_CODE_MAX + 1;

const ::google::protobuf::EnumDescriptor* ERR_CODE_descriptor();
inline const ::std::string& ERR_CODE_Name(ERR_CODE value) {
  return ::google::protobuf::internal::NameOfEnum(
    ERR_CODE_descriptor(), value);
}
inline bool ERR_CODE_Parse(
    const ::std::string& name, ERR_CODE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ERR_CODE>(
    ERR_CODE_descriptor(), name, value);
}
// ===================================================================

class LoginRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.LoginRequest) */ {
 public:
  LoginRequest();
  virtual ~LoginRequest();

  LoginRequest(const LoginRequest& from);

  inline LoginRequest& operator=(const LoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRequest& default_instance();

  void Swap(LoginRequest* other);

  // implements Message ----------------------------------------------

  inline LoginRequest* New() const { return New(NULL); }

  LoginRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRequest& from);
  void MergeFrom(const LoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes username = 1;
  bool has_username() const;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  void set_username(const char* value);
  void set_username(const void* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // optional string password = 2;
  bool has_password() const;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:pbmsg.LoginRequest)
 private:
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_password();
  inline void clear_has_password();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static LoginRequest* default_instance_;
};
// -------------------------------------------------------------------

class LoginRespond : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.LoginRespond) */ {
 public:
  LoginRespond();
  virtual ~LoginRespond();

  LoginRespond(const LoginRespond& from);

  inline LoginRespond& operator=(const LoginRespond& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRespond& default_instance();

  void Swap(LoginRespond* other);

  // implements Message ----------------------------------------------

  inline LoginRespond* New() const { return New(NULL); }

  LoginRespond* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRespond& from);
  void MergeFrom(const LoginRespond& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginRespond* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 ttl = 1;
  bool has_ttl() const;
  void clear_ttl();
  static const int kTtlFieldNumber = 1;
  ::google::protobuf::uint32 ttl() const;
  void set_ttl(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pbmsg.LoginRespond)
 private:
  inline void set_has_ttl();
  inline void clear_has_ttl();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 ttl_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static LoginRespond* default_instance_;
};
// -------------------------------------------------------------------

class Friend : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.Friend) */ {
 public:
  Friend();
  virtual ~Friend();

  Friend(const Friend& from);

  inline Friend& operator=(const Friend& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Friend& default_instance();

  void Swap(Friend* other);

  // implements Message ----------------------------------------------

  inline Friend* New() const { return New(NULL); }

  Friend* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Friend& from);
  void MergeFrom(const Friend& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Friend* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional bool online = 2;
  bool has_online() const;
  void clear_online();
  static const int kOnlineFieldNumber = 2;
  bool online() const;
  void set_online(bool value);

  // @@protoc_insertion_point(class_scope:pbmsg.Friend)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_online();
  inline void clear_has_online();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  bool online_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Friend* default_instance_;
};
// -------------------------------------------------------------------

class GetFriendsRespond : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.GetFriendsRespond) */ {
 public:
  GetFriendsRespond();
  virtual ~GetFriendsRespond();

  GetFriendsRespond(const GetFriendsRespond& from);

  inline GetFriendsRespond& operator=(const GetFriendsRespond& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetFriendsRespond& default_instance();

  void Swap(GetFriendsRespond* other);

  // implements Message ----------------------------------------------

  inline GetFriendsRespond* New() const { return New(NULL); }

  GetFriendsRespond* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetFriendsRespond& from);
  void MergeFrom(const GetFriendsRespond& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetFriendsRespond* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pbmsg.Friend friends = 1;
  int friends_size() const;
  void clear_friends();
  static const int kFriendsFieldNumber = 1;
  const ::pbmsg::Friend& friends(int index) const;
  ::pbmsg::Friend* mutable_friends(int index);
  ::pbmsg::Friend* add_friends();
  ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend >*
      mutable_friends();
  const ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend >&
      friends() const;

  // @@protoc_insertion_point(class_scope:pbmsg.GetFriendsRespond)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend > friends_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static GetFriendsRespond* default_instance_;
};
// -------------------------------------------------------------------

class SendMessageRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.SendMessageRequest) */ {
 public:
  SendMessageRequest();
  virtual ~SendMessageRequest();

  SendMessageRequest(const SendMessageRequest& from);

  inline SendMessageRequest& operator=(const SendMessageRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SendMessageRequest& default_instance();

  void Swap(SendMessageRequest* other);

  // implements Message ----------------------------------------------

  inline SendMessageRequest* New() const { return New(NULL); }

  SendMessageRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SendMessageRequest& from);
  void MergeFrom(const SendMessageRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SendMessageRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes receiver = 1;
  bool has_receiver() const;
  void clear_receiver();
  static const int kReceiverFieldNumber = 1;
  const ::std::string& receiver() const;
  void set_receiver(const ::std::string& value);
  void set_receiver(const char* value);
  void set_receiver(const void* value, size_t size);
  ::std::string* mutable_receiver();
  ::std::string* release_receiver();
  void set_allocated_receiver(::std::string* receiver);

  // required bytes text = 2;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 2;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  void set_text(const char* value);
  void set_text(const void* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // @@protoc_insertion_point(class_scope:pbmsg.SendMessageRequest)
 private:
  inline void set_has_receiver();
  inline void clear_has_receiver();
  inline void set_has_text();
  inline void clear_has_text();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr receiver_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static SendMessageRequest* default_instance_;
};
// -------------------------------------------------------------------

class FriendNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.FriendNotify) */ {
 public:
  FriendNotify();
  virtual ~FriendNotify();

  FriendNotify(const FriendNotify& from);

  inline FriendNotify& operator=(const FriendNotify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FriendNotify& default_instance();

  void Swap(FriendNotify* other);

  // implements Message ----------------------------------------------

  inline FriendNotify* New() const { return New(NULL); }

  FriendNotify* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FriendNotify& from);
  void MergeFrom(const FriendNotify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FriendNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional bool online = 2;
  bool has_online() const;
  void clear_online();
  static const int kOnlineFieldNumber = 2;
  bool online() const;
  void set_online(bool value);

  // @@protoc_insertion_point(class_scope:pbmsg.FriendNotify)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_online();
  inline void clear_has_online();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  bool online_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static FriendNotify* default_instance_;
};
// -------------------------------------------------------------------

class MessageNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.MessageNotify) */ {
 public:
  MessageNotify();
  virtual ~MessageNotify();

  MessageNotify(const MessageNotify& from);

  inline MessageNotify& operator=(const MessageNotify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageNotify& default_instance();

  void Swap(MessageNotify* other);

  // implements Message ----------------------------------------------

  inline MessageNotify* New() const { return New(NULL); }

  MessageNotify* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageNotify& from);
  void MergeFrom(const MessageNotify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes sender = 1;
  bool has_sender() const;
  void clear_sender();
  static const int kSenderFieldNumber = 1;
  const ::std::string& sender() const;
  void set_sender(const ::std::string& value);
  void set_sender(const char* value);
  void set_sender(const void* value, size_t size);
  ::std::string* mutable_sender();
  ::std::string* release_sender();
  void set_allocated_sender(::std::string* sender);

  // required bytes text = 2;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 2;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  void set_text(const char* value);
  void set_text(const void* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // required string timestamp = 3;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  const ::std::string& timestamp() const;
  void set_timestamp(const ::std::string& value);
  void set_timestamp(const char* value);
  void set_timestamp(const char* value, size_t size);
  ::std::string* mutable_timestamp();
  ::std::string* release_timestamp();
  void set_allocated_timestamp(::std::string* timestamp);

  // @@protoc_insertion_point(class_scope:pbmsg.MessageNotify)
 private:
  inline void set_has_sender();
  inline void clear_has_sender();
  inline void set_has_text();
  inline void clear_has_text();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr sender_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  ::google::protobuf::internal::ArenaStringPtr timestamp_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static MessageNotify* default_instance_;
};
// -------------------------------------------------------------------

class WelcomeNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.WelcomeNotify) */ {
 public:
  WelcomeNotify();
  virtual ~WelcomeNotify();

  WelcomeNotify(const WelcomeNotify& from);

  inline WelcomeNotify& operator=(const WelcomeNotify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WelcomeNotify& default_instance();

  void Swap(WelcomeNotify* other);

  // implements Message ----------------------------------------------

  inline WelcomeNotify* New() const { return New(NULL); }

  WelcomeNotify* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WelcomeNotify& from);
  void MergeFrom(const WelcomeNotify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WelcomeNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes text = 1;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 1;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  void set_text(const char* value);
  void set_text(const void* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // @@protoc_insertion_point(class_scope:pbmsg.WelcomeNotify)
 private:
  inline void set_has_text();
  inline void clear_has_text();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static WelcomeNotify* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  inline Request* New() const { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .pbmsg.LoginRequest login = 1;
  bool has_login() const;
  void clear_login();
  static const int kLoginFieldNumber = 1;
  const ::pbmsg::LoginRequest& login() const;
  ::pbmsg::LoginRequest* mutable_login();
  ::pbmsg::LoginRequest* release_login();
  void set_allocated_login(::pbmsg::LoginRequest* login);

  // optional .pbmsg.SendMessageRequest sendMessage = 2;
  bool has_sendmessage() const;
  void clear_sendmessage();
  static const int kSendMessageFieldNumber = 2;
  const ::pbmsg::SendMessageRequest& sendmessage() const;
  ::pbmsg::SendMessageRequest* mutable_sendmessage();
  ::pbmsg::SendMessageRequest* release_sendmessage();
  void set_allocated_sendmessage(::pbmsg::SendMessageRequest* sendmessage);

  // @@protoc_insertion_point(class_scope:pbmsg.Request)
 private:
  inline void set_has_login();
  inline void clear_has_login();
  inline void set_has_sendmessage();
  inline void clear_has_sendmessage();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::pbmsg::LoginRequest* login_;
  ::pbmsg::SendMessageRequest* sendmessage_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Respond : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.Respond) */ {
 public:
  Respond();
  virtual ~Respond();

  Respond(const Respond& from);

  inline Respond& operator=(const Respond& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Respond& default_instance();

  void Swap(Respond* other);

  // implements Message ----------------------------------------------

  inline Respond* New() const { return New(NULL); }

  Respond* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Respond& from);
  void MergeFrom(const Respond& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Respond* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  bool result() const;
  void set_result(bool value);

  // required bool lastRespond = 2;
  bool has_lastrespond() const;
  void clear_lastrespond();
  static const int kLastRespondFieldNumber = 2;
  bool lastrespond() const;
  void set_lastrespond(bool value);

  // optional bytes errorDescribe = 3;
  bool has_errordescribe() const;
  void clear_errordescribe();
  static const int kErrorDescribeFieldNumber = 3;
  const ::std::string& errordescribe() const;
  void set_errordescribe(const ::std::string& value);
  void set_errordescribe(const char* value);
  void set_errordescribe(const void* value, size_t size);
  ::std::string* mutable_errordescribe();
  ::std::string* release_errordescribe();
  void set_allocated_errordescribe(::std::string* errordescribe);

  // optional .pbmsg.LoginRespond login = 4;
  bool has_login() const;
  void clear_login();
  static const int kLoginFieldNumber = 4;
  const ::pbmsg::LoginRespond& login() const;
  ::pbmsg::LoginRespond* mutable_login();
  ::pbmsg::LoginRespond* release_login();
  void set_allocated_login(::pbmsg::LoginRespond* login);

  // optional .pbmsg.GetFriendsRespond friends = 5;
  bool has_friends() const;
  void clear_friends();
  static const int kFriendsFieldNumber = 5;
  const ::pbmsg::GetFriendsRespond& friends() const;
  ::pbmsg::GetFriendsRespond* mutable_friends();
  ::pbmsg::GetFriendsRespond* release_friends();
  void set_allocated_friends(::pbmsg::GetFriendsRespond* friends);

  // @@protoc_insertion_point(class_scope:pbmsg.Respond)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_lastrespond();
  inline void clear_has_lastrespond();
  inline void set_has_errordescribe();
  inline void clear_has_errordescribe();
  inline void set_has_login();
  inline void clear_has_login();
  inline void set_has_friends();
  inline void clear_has_friends();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr errordescribe_;
  ::pbmsg::LoginRespond* login_;
  ::pbmsg::GetFriendsRespond* friends_;
  bool result_;
  bool lastrespond_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Respond* default_instance_;
};
// -------------------------------------------------------------------

class Notify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.Notify) */ {
 public:
  Notify();
  virtual ~Notify();

  Notify(const Notify& from);

  inline Notify& operator=(const Notify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Notify& default_instance();

  void Swap(Notify* other);

  // implements Message ----------------------------------------------

  inline Notify* New() const { return New(NULL); }

  Notify* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Notify& from);
  void MergeFrom(const Notify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Notify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .pbmsg.FriendNotify friend = 1;
  bool has_friend_() const;
  void clear_friend_();
  static const int kFriendFieldNumber = 1;
  const ::pbmsg::FriendNotify& friend_() const;
  ::pbmsg::FriendNotify* mutable_friend_();
  ::pbmsg::FriendNotify* release_friend_();
  void set_allocated_friend_(::pbmsg::FriendNotify* friend_);

  // optional .pbmsg.MessageNotify msg = 2;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::pbmsg::MessageNotify& msg() const;
  ::pbmsg::MessageNotify* mutable_msg();
  ::pbmsg::MessageNotify* release_msg();
  void set_allocated_msg(::pbmsg::MessageNotify* msg);

  // optional .pbmsg.WelcomeNotify welcome = 3;
  bool has_welcome() const;
  void clear_welcome();
  static const int kWelcomeFieldNumber = 3;
  const ::pbmsg::WelcomeNotify& welcome() const;
  ::pbmsg::WelcomeNotify* mutable_welcome();
  ::pbmsg::WelcomeNotify* release_welcome();
  void set_allocated_welcome(::pbmsg::WelcomeNotify* welcome);

  // @@protoc_insertion_point(class_scope:pbmsg.Notify)
 private:
  inline void set_has_friend_();
  inline void clear_has_friend_();
  inline void set_has_msg();
  inline void clear_has_msg();
  inline void set_has_welcome();
  inline void clear_has_welcome();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::pbmsg::FriendNotify* friend__;
  ::pbmsg::MessageNotify* msg_;
  ::pbmsg::WelcomeNotify* welcome_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Notify* default_instance_;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmsg.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .pbmsg.MSG msgType = 1;
  bool has_msgtype() const;
  void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  ::pbmsg::MSG msgtype() const;
  void set_msgtype(::pbmsg::MSG value);

  // required fixed32 sequence = 2;
  bool has_sequence() const;
  void clear_sequence();
  static const int kSequenceFieldNumber = 2;
  ::google::protobuf::uint32 sequence() const;
  void set_sequence(::google::protobuf::uint32 value);

  // optional fixed32 sessionId = 3;
  bool has_sessionid() const;
  void clear_sessionid();
  static const int kSessionIdFieldNumber = 3;
  ::google::protobuf::uint32 sessionid() const;
  void set_sessionid(::google::protobuf::uint32 value);

  // optional .pbmsg.Request request = 4;
  bool has_request() const;
  void clear_request();
  static const int kRequestFieldNumber = 4;
  const ::pbmsg::Request& request() const;
  ::pbmsg::Request* mutable_request();
  ::pbmsg::Request* release_request();
  void set_allocated_request(::pbmsg::Request* request);

  // optional .pbmsg.Respond respond = 5;
  bool has_respond() const;
  void clear_respond();
  static const int kRespondFieldNumber = 5;
  const ::pbmsg::Respond& respond() const;
  ::pbmsg::Respond* mutable_respond();
  ::pbmsg::Respond* release_respond();
  void set_allocated_respond(::pbmsg::Respond* respond);

  // optional .pbmsg.Notify notify = 6;
  bool has_notify() const;
  void clear_notify();
  static const int kNotifyFieldNumber = 6;
  const ::pbmsg::Notify& notify() const;
  ::pbmsg::Notify* mutable_notify();
  ::pbmsg::Notify* release_notify();
  void set_allocated_notify(::pbmsg::Notify* notify);

  // @@protoc_insertion_point(class_scope:pbmsg.Message)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_sessionid();
  inline void clear_has_sessionid();
  inline void set_has_request();
  inline void clear_has_request();
  inline void set_has_respond();
  inline void clear_has_respond();
  inline void set_has_notify();
  inline void clear_has_notify();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  ::google::protobuf::uint32 sequence_;
  ::pbmsg::Request* request_;
  ::pbmsg::Respond* respond_;
  ::pbmsg::Notify* notify_;
  ::google::protobuf::uint32 sessionid_;
  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static Message* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginRequest

// required bytes username = 1;
inline bool LoginRequest::has_username() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRequest::set_has_username() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRequest::clear_has_username() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_username();
}
inline const ::std::string& LoginRequest::username() const {
  // @@protoc_insertion_point(field_get:pbmsg.LoginRequest.username)
  return username_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_username(const ::std::string& value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.LoginRequest.username)
}
inline void LoginRequest::set_username(const char* value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.LoginRequest.username)
}
inline void LoginRequest::set_username(const void* value, size_t size) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.LoginRequest.username)
}
inline ::std::string* LoginRequest::mutable_username() {
  set_has_username();
  // @@protoc_insertion_point(field_mutable:pbmsg.LoginRequest.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRequest::release_username() {
  // @@protoc_insertion_point(field_release:pbmsg.LoginRequest.username)
  clear_has_username();
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    set_has_username();
  } else {
    clear_has_username();
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.LoginRequest.username)
}

// optional string password = 2;
inline bool LoginRequest::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginRequest::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginRequest::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginRequest::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_password();
}
inline const ::std::string& LoginRequest::password() const {
  // @@protoc_insertion_point(field_get:pbmsg.LoginRequest.password)
  return password_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_password(const ::std::string& value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.LoginRequest.password)
}
inline void LoginRequest::set_password(const char* value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.LoginRequest.password)
}
inline void LoginRequest::set_password(const char* value, size_t size) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.LoginRequest.password)
}
inline ::std::string* LoginRequest::mutable_password() {
  set_has_password();
  // @@protoc_insertion_point(field_mutable:pbmsg.LoginRequest.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRequest::release_password() {
  // @@protoc_insertion_point(field_release:pbmsg.LoginRequest.password)
  clear_has_password();
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    set_has_password();
  } else {
    clear_has_password();
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.LoginRequest.password)
}

// -------------------------------------------------------------------

// LoginRespond

// required fixed32 ttl = 1;
inline bool LoginRespond::has_ttl() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRespond::set_has_ttl() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRespond::clear_has_ttl() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRespond::clear_ttl() {
  ttl_ = 0u;
  clear_has_ttl();
}
inline ::google::protobuf::uint32 LoginRespond::ttl() const {
  // @@protoc_insertion_point(field_get:pbmsg.LoginRespond.ttl)
  return ttl_;
}
inline void LoginRespond::set_ttl(::google::protobuf::uint32 value) {
  set_has_ttl();
  ttl_ = value;
  // @@protoc_insertion_point(field_set:pbmsg.LoginRespond.ttl)
}

// -------------------------------------------------------------------

// Friend

// required bytes name = 1;
inline bool Friend::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Friend::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Friend::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Friend::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Friend::name() const {
  // @@protoc_insertion_point(field_get:pbmsg.Friend.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Friend::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.Friend.name)
}
inline void Friend::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.Friend.name)
}
inline void Friend::set_name(const void* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.Friend.name)
}
inline ::std::string* Friend::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:pbmsg.Friend.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Friend::release_name() {
  // @@protoc_insertion_point(field_release:pbmsg.Friend.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Friend::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Friend.name)
}

// optional bool online = 2;
inline bool Friend::has_online() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Friend::set_has_online() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Friend::clear_has_online() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Friend::clear_online() {
  online_ = false;
  clear_has_online();
}
inline bool Friend::online() const {
  // @@protoc_insertion_point(field_get:pbmsg.Friend.online)
  return online_;
}
inline void Friend::set_online(bool value) {
  set_has_online();
  online_ = value;
  // @@protoc_insertion_point(field_set:pbmsg.Friend.online)
}

// -------------------------------------------------------------------

// GetFriendsRespond

// repeated .pbmsg.Friend friends = 1;
inline int GetFriendsRespond::friends_size() const {
  return friends_.size();
}
inline void GetFriendsRespond::clear_friends() {
  friends_.Clear();
}
inline const ::pbmsg::Friend& GetFriendsRespond::friends(int index) const {
  // @@protoc_insertion_point(field_get:pbmsg.GetFriendsRespond.friends)
  return friends_.Get(index);
}
inline ::pbmsg::Friend* GetFriendsRespond::mutable_friends(int index) {
  // @@protoc_insertion_point(field_mutable:pbmsg.GetFriendsRespond.friends)
  return friends_.Mutable(index);
}
inline ::pbmsg::Friend* GetFriendsRespond::add_friends() {
  // @@protoc_insertion_point(field_add:pbmsg.GetFriendsRespond.friends)
  return friends_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend >*
GetFriendsRespond::mutable_friends() {
  // @@protoc_insertion_point(field_mutable_list:pbmsg.GetFriendsRespond.friends)
  return &friends_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pbmsg::Friend >&
GetFriendsRespond::friends() const {
  // @@protoc_insertion_point(field_list:pbmsg.GetFriendsRespond.friends)
  return friends_;
}

// -------------------------------------------------------------------

// SendMessageRequest

// optional bytes receiver = 1;
inline bool SendMessageRequest::has_receiver() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SendMessageRequest::set_has_receiver() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SendMessageRequest::clear_has_receiver() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SendMessageRequest::clear_receiver() {
  receiver_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_receiver();
}
inline const ::std::string& SendMessageRequest::receiver() const {
  // @@protoc_insertion_point(field_get:pbmsg.SendMessageRequest.receiver)
  return receiver_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMessageRequest::set_receiver(const ::std::string& value) {
  set_has_receiver();
  receiver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.SendMessageRequest.receiver)
}
inline void SendMessageRequest::set_receiver(const char* value) {
  set_has_receiver();
  receiver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.SendMessageRequest.receiver)
}
inline void SendMessageRequest::set_receiver(const void* value, size_t size) {
  set_has_receiver();
  receiver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.SendMessageRequest.receiver)
}
inline ::std::string* SendMessageRequest::mutable_receiver() {
  set_has_receiver();
  // @@protoc_insertion_point(field_mutable:pbmsg.SendMessageRequest.receiver)
  return receiver_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMessageRequest::release_receiver() {
  // @@protoc_insertion_point(field_release:pbmsg.SendMessageRequest.receiver)
  clear_has_receiver();
  return receiver_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMessageRequest::set_allocated_receiver(::std::string* receiver) {
  if (receiver != NULL) {
    set_has_receiver();
  } else {
    clear_has_receiver();
  }
  receiver_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), receiver);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.SendMessageRequest.receiver)
}

// required bytes text = 2;
inline bool SendMessageRequest::has_text() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SendMessageRequest::set_has_text() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SendMessageRequest::clear_has_text() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SendMessageRequest::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_text();
}
inline const ::std::string& SendMessageRequest::text() const {
  // @@protoc_insertion_point(field_get:pbmsg.SendMessageRequest.text)
  return text_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMessageRequest::set_text(const ::std::string& value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.SendMessageRequest.text)
}
inline void SendMessageRequest::set_text(const char* value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.SendMessageRequest.text)
}
inline void SendMessageRequest::set_text(const void* value, size_t size) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.SendMessageRequest.text)
}
inline ::std::string* SendMessageRequest::mutable_text() {
  set_has_text();
  // @@protoc_insertion_point(field_mutable:pbmsg.SendMessageRequest.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMessageRequest::release_text() {
  // @@protoc_insertion_point(field_release:pbmsg.SendMessageRequest.text)
  clear_has_text();
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMessageRequest::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    set_has_text();
  } else {
    clear_has_text();
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.SendMessageRequest.text)
}

// -------------------------------------------------------------------

// FriendNotify

// required bytes name = 1;
inline bool FriendNotify::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FriendNotify::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FriendNotify::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FriendNotify::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& FriendNotify::name() const {
  // @@protoc_insertion_point(field_get:pbmsg.FriendNotify.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FriendNotify::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.FriendNotify.name)
}
inline void FriendNotify::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.FriendNotify.name)
}
inline void FriendNotify::set_name(const void* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.FriendNotify.name)
}
inline ::std::string* FriendNotify::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:pbmsg.FriendNotify.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FriendNotify::release_name() {
  // @@protoc_insertion_point(field_release:pbmsg.FriendNotify.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FriendNotify::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.FriendNotify.name)
}

// optional bool online = 2;
inline bool FriendNotify::has_online() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FriendNotify::set_has_online() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FriendNotify::clear_has_online() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FriendNotify::clear_online() {
  online_ = false;
  clear_has_online();
}
inline bool FriendNotify::online() const {
  // @@protoc_insertion_point(field_get:pbmsg.FriendNotify.online)
  return online_;
}
inline void FriendNotify::set_online(bool value) {
  set_has_online();
  online_ = value;
  // @@protoc_insertion_point(field_set:pbmsg.FriendNotify.online)
}

// -------------------------------------------------------------------

// MessageNotify

// required bytes sender = 1;
inline bool MessageNotify::has_sender() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageNotify::set_has_sender() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageNotify::clear_has_sender() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageNotify::clear_sender() {
  sender_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sender();
}
inline const ::std::string& MessageNotify::sender() const {
  // @@protoc_insertion_point(field_get:pbmsg.MessageNotify.sender)
  return sender_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageNotify::set_sender(const ::std::string& value) {
  set_has_sender();
  sender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.MessageNotify.sender)
}
inline void MessageNotify::set_sender(const char* value) {
  set_has_sender();
  sender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.MessageNotify.sender)
}
inline void MessageNotify::set_sender(const void* value, size_t size) {
  set_has_sender();
  sender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.MessageNotify.sender)
}
inline ::std::string* MessageNotify::mutable_sender() {
  set_has_sender();
  // @@protoc_insertion_point(field_mutable:pbmsg.MessageNotify.sender)
  return sender_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageNotify::release_sender() {
  // @@protoc_insertion_point(field_release:pbmsg.MessageNotify.sender)
  clear_has_sender();
  return sender_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageNotify::set_allocated_sender(::std::string* sender) {
  if (sender != NULL) {
    set_has_sender();
  } else {
    clear_has_sender();
  }
  sender_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sender);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.MessageNotify.sender)
}

// required bytes text = 2;
inline bool MessageNotify::has_text() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageNotify::set_has_text() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageNotify::clear_has_text() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageNotify::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_text();
}
inline const ::std::string& MessageNotify::text() const {
  // @@protoc_insertion_point(field_get:pbmsg.MessageNotify.text)
  return text_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageNotify::set_text(const ::std::string& value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.MessageNotify.text)
}
inline void MessageNotify::set_text(const char* value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.MessageNotify.text)
}
inline void MessageNotify::set_text(const void* value, size_t size) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.MessageNotify.text)
}
inline ::std::string* MessageNotify::mutable_text() {
  set_has_text();
  // @@protoc_insertion_point(field_mutable:pbmsg.MessageNotify.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageNotify::release_text() {
  // @@protoc_insertion_point(field_release:pbmsg.MessageNotify.text)
  clear_has_text();
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageNotify::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    set_has_text();
  } else {
    clear_has_text();
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.MessageNotify.text)
}

// required string timestamp = 3;
inline bool MessageNotify::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageNotify::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageNotify::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageNotify::clear_timestamp() {
  timestamp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_timestamp();
}
inline const ::std::string& MessageNotify::timestamp() const {
  // @@protoc_insertion_point(field_get:pbmsg.MessageNotify.timestamp)
  return timestamp_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageNotify::set_timestamp(const ::std::string& value) {
  set_has_timestamp();
  timestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.MessageNotify.timestamp)
}
inline void MessageNotify::set_timestamp(const char* value) {
  set_has_timestamp();
  timestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.MessageNotify.timestamp)
}
inline void MessageNotify::set_timestamp(const char* value, size_t size) {
  set_has_timestamp();
  timestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.MessageNotify.timestamp)
}
inline ::std::string* MessageNotify::mutable_timestamp() {
  set_has_timestamp();
  // @@protoc_insertion_point(field_mutable:pbmsg.MessageNotify.timestamp)
  return timestamp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageNotify::release_timestamp() {
  // @@protoc_insertion_point(field_release:pbmsg.MessageNotify.timestamp)
  clear_has_timestamp();
  return timestamp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageNotify::set_allocated_timestamp(::std::string* timestamp) {
  if (timestamp != NULL) {
    set_has_timestamp();
  } else {
    clear_has_timestamp();
  }
  timestamp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), timestamp);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.MessageNotify.timestamp)
}

// -------------------------------------------------------------------

// WelcomeNotify

// required bytes text = 1;
inline bool WelcomeNotify::has_text() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WelcomeNotify::set_has_text() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WelcomeNotify::clear_has_text() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WelcomeNotify::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_text();
}
inline const ::std::string& WelcomeNotify::text() const {
  // @@protoc_insertion_point(field_get:pbmsg.WelcomeNotify.text)
  return text_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WelcomeNotify::set_text(const ::std::string& value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.WelcomeNotify.text)
}
inline void WelcomeNotify::set_text(const char* value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.WelcomeNotify.text)
}
inline void WelcomeNotify::set_text(const void* value, size_t size) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.WelcomeNotify.text)
}
inline ::std::string* WelcomeNotify::mutable_text() {
  set_has_text();
  // @@protoc_insertion_point(field_mutable:pbmsg.WelcomeNotify.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WelcomeNotify::release_text() {
  // @@protoc_insertion_point(field_release:pbmsg.WelcomeNotify.text)
  clear_has_text();
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WelcomeNotify::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    set_has_text();
  } else {
    clear_has_text();
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.WelcomeNotify.text)
}

// -------------------------------------------------------------------

// Request

// optional .pbmsg.LoginRequest login = 1;
inline bool Request::has_login() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_login() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_login() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_login() {
  if (login_ != NULL) login_->::pbmsg::LoginRequest::Clear();
  clear_has_login();
}
inline const ::pbmsg::LoginRequest& Request::login() const {
  // @@protoc_insertion_point(field_get:pbmsg.Request.login)
  return login_ != NULL ? *login_ : *default_instance_->login_;
}
inline ::pbmsg::LoginRequest* Request::mutable_login() {
  set_has_login();
  if (login_ == NULL) {
    login_ = new ::pbmsg::LoginRequest;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Request.login)
  return login_;
}
inline ::pbmsg::LoginRequest* Request::release_login() {
  // @@protoc_insertion_point(field_release:pbmsg.Request.login)
  clear_has_login();
  ::pbmsg::LoginRequest* temp = login_;
  login_ = NULL;
  return temp;
}
inline void Request::set_allocated_login(::pbmsg::LoginRequest* login) {
  delete login_;
  login_ = login;
  if (login) {
    set_has_login();
  } else {
    clear_has_login();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Request.login)
}

// optional .pbmsg.SendMessageRequest sendMessage = 2;
inline bool Request::has_sendmessage() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_sendmessage() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_sendmessage() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_sendmessage() {
  if (sendmessage_ != NULL) sendmessage_->::pbmsg::SendMessageRequest::Clear();
  clear_has_sendmessage();
}
inline const ::pbmsg::SendMessageRequest& Request::sendmessage() const {
  // @@protoc_insertion_point(field_get:pbmsg.Request.sendMessage)
  return sendmessage_ != NULL ? *sendmessage_ : *default_instance_->sendmessage_;
}
inline ::pbmsg::SendMessageRequest* Request::mutable_sendmessage() {
  set_has_sendmessage();
  if (sendmessage_ == NULL) {
    sendmessage_ = new ::pbmsg::SendMessageRequest;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Request.sendMessage)
  return sendmessage_;
}
inline ::pbmsg::SendMessageRequest* Request::release_sendmessage() {
  // @@protoc_insertion_point(field_release:pbmsg.Request.sendMessage)
  clear_has_sendmessage();
  ::pbmsg::SendMessageRequest* temp = sendmessage_;
  sendmessage_ = NULL;
  return temp;
}
inline void Request::set_allocated_sendmessage(::pbmsg::SendMessageRequest* sendmessage) {
  delete sendmessage_;
  sendmessage_ = sendmessage;
  if (sendmessage) {
    set_has_sendmessage();
  } else {
    clear_has_sendmessage();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Request.sendMessage)
}

// -------------------------------------------------------------------

// Respond

// required bool result = 1;
inline bool Respond::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Respond::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Respond::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Respond::clear_result() {
  result_ = false;
  clear_has_result();
}
inline bool Respond::result() const {
  // @@protoc_insertion_point(field_get:pbmsg.Respond.result)
  return result_;
}
inline void Respond::set_result(bool value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:pbmsg.Respond.result)
}

// required bool lastRespond = 2;
inline bool Respond::has_lastrespond() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Respond::set_has_lastrespond() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Respond::clear_has_lastrespond() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Respond::clear_lastrespond() {
  lastrespond_ = false;
  clear_has_lastrespond();
}
inline bool Respond::lastrespond() const {
  // @@protoc_insertion_point(field_get:pbmsg.Respond.lastRespond)
  return lastrespond_;
}
inline void Respond::set_lastrespond(bool value) {
  set_has_lastrespond();
  lastrespond_ = value;
  // @@protoc_insertion_point(field_set:pbmsg.Respond.lastRespond)
}

// optional bytes errorDescribe = 3;
inline bool Respond::has_errordescribe() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Respond::set_has_errordescribe() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Respond::clear_has_errordescribe() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Respond::clear_errordescribe() {
  errordescribe_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_errordescribe();
}
inline const ::std::string& Respond::errordescribe() const {
  // @@protoc_insertion_point(field_get:pbmsg.Respond.errorDescribe)
  return errordescribe_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Respond::set_errordescribe(const ::std::string& value) {
  set_has_errordescribe();
  errordescribe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pbmsg.Respond.errorDescribe)
}
inline void Respond::set_errordescribe(const char* value) {
  set_has_errordescribe();
  errordescribe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pbmsg.Respond.errorDescribe)
}
inline void Respond::set_errordescribe(const void* value, size_t size) {
  set_has_errordescribe();
  errordescribe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pbmsg.Respond.errorDescribe)
}
inline ::std::string* Respond::mutable_errordescribe() {
  set_has_errordescribe();
  // @@protoc_insertion_point(field_mutable:pbmsg.Respond.errorDescribe)
  return errordescribe_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Respond::release_errordescribe() {
  // @@protoc_insertion_point(field_release:pbmsg.Respond.errorDescribe)
  clear_has_errordescribe();
  return errordescribe_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Respond::set_allocated_errordescribe(::std::string* errordescribe) {
  if (errordescribe != NULL) {
    set_has_errordescribe();
  } else {
    clear_has_errordescribe();
  }
  errordescribe_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), errordescribe);
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Respond.errorDescribe)
}

// optional .pbmsg.LoginRespond login = 4;
inline bool Respond::has_login() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Respond::set_has_login() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Respond::clear_has_login() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Respond::clear_login() {
  if (login_ != NULL) login_->::pbmsg::LoginRespond::Clear();
  clear_has_login();
}
inline const ::pbmsg::LoginRespond& Respond::login() const {
  // @@protoc_insertion_point(field_get:pbmsg.Respond.login)
  return login_ != NULL ? *login_ : *default_instance_->login_;
}
inline ::pbmsg::LoginRespond* Respond::mutable_login() {
  set_has_login();
  if (login_ == NULL) {
    login_ = new ::pbmsg::LoginRespond;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Respond.login)
  return login_;
}
inline ::pbmsg::LoginRespond* Respond::release_login() {
  // @@protoc_insertion_point(field_release:pbmsg.Respond.login)
  clear_has_login();
  ::pbmsg::LoginRespond* temp = login_;
  login_ = NULL;
  return temp;
}
inline void Respond::set_allocated_login(::pbmsg::LoginRespond* login) {
  delete login_;
  login_ = login;
  if (login) {
    set_has_login();
  } else {
    clear_has_login();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Respond.login)
}

// optional .pbmsg.GetFriendsRespond friends = 5;
inline bool Respond::has_friends() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Respond::set_has_friends() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Respond::clear_has_friends() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Respond::clear_friends() {
  if (friends_ != NULL) friends_->::pbmsg::GetFriendsRespond::Clear();
  clear_has_friends();
}
inline const ::pbmsg::GetFriendsRespond& Respond::friends() const {
  // @@protoc_insertion_point(field_get:pbmsg.Respond.friends)
  return friends_ != NULL ? *friends_ : *default_instance_->friends_;
}
inline ::pbmsg::GetFriendsRespond* Respond::mutable_friends() {
  set_has_friends();
  if (friends_ == NULL) {
    friends_ = new ::pbmsg::GetFriendsRespond;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Respond.friends)
  return friends_;
}
inline ::pbmsg::GetFriendsRespond* Respond::release_friends() {
  // @@protoc_insertion_point(field_release:pbmsg.Respond.friends)
  clear_has_friends();
  ::pbmsg::GetFriendsRespond* temp = friends_;
  friends_ = NULL;
  return temp;
}
inline void Respond::set_allocated_friends(::pbmsg::GetFriendsRespond* friends) {
  delete friends_;
  friends_ = friends;
  if (friends) {
    set_has_friends();
  } else {
    clear_has_friends();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Respond.friends)
}

// -------------------------------------------------------------------

// Notify

// optional .pbmsg.FriendNotify friend = 1;
inline bool Notify::has_friend_() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Notify::set_has_friend_() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Notify::clear_has_friend_() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Notify::clear_friend_() {
  if (friend__ != NULL) friend__->::pbmsg::FriendNotify::Clear();
  clear_has_friend_();
}
inline const ::pbmsg::FriendNotify& Notify::friend_() const {
  // @@protoc_insertion_point(field_get:pbmsg.Notify.friend)
  return friend__ != NULL ? *friend__ : *default_instance_->friend__;
}
inline ::pbmsg::FriendNotify* Notify::mutable_friend_() {
  set_has_friend_();
  if (friend__ == NULL) {
    friend__ = new ::pbmsg::FriendNotify;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Notify.friend)
  return friend__;
}
inline ::pbmsg::FriendNotify* Notify::release_friend_() {
  // @@protoc_insertion_point(field_release:pbmsg.Notify.friend)
  clear_has_friend_();
  ::pbmsg::FriendNotify* temp = friend__;
  friend__ = NULL;
  return temp;
}
inline void Notify::set_allocated_friend_(::pbmsg::FriendNotify* friend_) {
  delete friend__;
  friend__ = friend_;
  if (friend_) {
    set_has_friend_();
  } else {
    clear_has_friend_();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Notify.friend)
}

// optional .pbmsg.MessageNotify msg = 2;
inline bool Notify::has_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Notify::set_has_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Notify::clear_has_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Notify::clear_msg() {
  if (msg_ != NULL) msg_->::pbmsg::MessageNotify::Clear();
  clear_has_msg();
}
inline const ::pbmsg::MessageNotify& Notify::msg() const {
  // @@protoc_insertion_point(field_get:pbmsg.Notify.msg)
  return msg_ != NULL ? *msg_ : *default_instance_->msg_;
}
inline ::pbmsg::MessageNotify* Notify::mutable_msg() {
  set_has_msg();
  if (msg_ == NULL) {
    msg_ = new ::pbmsg::MessageNotify;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Notify.msg)
  return msg_;
}
inline ::pbmsg::MessageNotify* Notify::release_msg() {
  // @@protoc_insertion_point(field_release:pbmsg.Notify.msg)
  clear_has_msg();
  ::pbmsg::MessageNotify* temp = msg_;
  msg_ = NULL;
  return temp;
}
inline void Notify::set_allocated_msg(::pbmsg::MessageNotify* msg) {
  delete msg_;
  msg_ = msg;
  if (msg) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Notify.msg)
}

// optional .pbmsg.WelcomeNotify welcome = 3;
inline bool Notify::has_welcome() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Notify::set_has_welcome() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Notify::clear_has_welcome() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Notify::clear_welcome() {
  if (welcome_ != NULL) welcome_->::pbmsg::WelcomeNotify::Clear();
  clear_has_welcome();
}
inline const ::pbmsg::WelcomeNotify& Notify::welcome() const {
  // @@protoc_insertion_point(field_get:pbmsg.Notify.welcome)
  return welcome_ != NULL ? *welcome_ : *default_instance_->welcome_;
}
inline ::pbmsg::WelcomeNotify* Notify::mutable_welcome() {
  set_has_welcome();
  if (welcome_ == NULL) {
    welcome_ = new ::pbmsg::WelcomeNotify;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Notify.welcome)
  return welcome_;
}
inline ::pbmsg::WelcomeNotify* Notify::release_welcome() {
  // @@protoc_insertion_point(field_release:pbmsg.Notify.welcome)
  clear_has_welcome();
  ::pbmsg::WelcomeNotify* temp = welcome_;
  welcome_ = NULL;
  return temp;
}
inline void Notify::set_allocated_welcome(::pbmsg::WelcomeNotify* welcome) {
  delete welcome_;
  welcome_ = welcome;
  if (welcome) {
    set_has_welcome();
  } else {
    clear_has_welcome();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Notify.welcome)
}

// -------------------------------------------------------------------

// Message

// required .pbmsg.MSG msgType = 1;
inline bool Message::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_msgtype() {
  msgtype_ = 10001;
  clear_has_msgtype();
}
inline ::pbmsg::MSG Message::msgtype() const {
  // @@protoc_insertion_point(field_get:pbmsg.Message.msgType)
  return static_cast< ::pbmsg::MSG >(msgtype_);
}
inline void Message::set_msgtype(::pbmsg::MSG value) {
  assert(::pbmsg::MSG_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:pbmsg.Message.msgType)
}

// required fixed32 sequence = 2;
inline bool Message::has_sequence() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_sequence() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_sequence() {
  sequence_ = 0u;
  clear_has_sequence();
}
inline ::google::protobuf::uint32 Message::sequence() const {
  // @@protoc_insertion_point(field_get:pbmsg.Message.sequence)
  return sequence_;
}
inline void Message::set_sequence(::google::protobuf::uint32 value) {
  set_has_sequence();
  sequence_ = value;
  // @@protoc_insertion_point(field_set:pbmsg.Message.sequence)
}

// optional fixed32 sessionId = 3;
inline bool Message::has_sessionid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_sessionid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_sessionid() {
  sessionid_ = 0u;
  clear_has_sessionid();
}
inline ::google::protobuf::uint32 Message::sessionid() const {
  // @@protoc_insertion_point(field_get:pbmsg.Message.sessionId)
  return sessionid_;
}
inline void Message::set_sessionid(::google::protobuf::uint32 value) {
  set_has_sessionid();
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:pbmsg.Message.sessionId)
}

// optional .pbmsg.Request request = 4;
inline bool Message::has_request() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_request() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_request() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_request() {
  if (request_ != NULL) request_->::pbmsg::Request::Clear();
  clear_has_request();
}
inline const ::pbmsg::Request& Message::request() const {
  // @@protoc_insertion_point(field_get:pbmsg.Message.request)
  return request_ != NULL ? *request_ : *default_instance_->request_;
}
inline ::pbmsg::Request* Message::mutable_request() {
  set_has_request();
  if (request_ == NULL) {
    request_ = new ::pbmsg::Request;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Message.request)
  return request_;
}
inline ::pbmsg::Request* Message::release_request() {
  // @@protoc_insertion_point(field_release:pbmsg.Message.request)
  clear_has_request();
  ::pbmsg::Request* temp = request_;
  request_ = NULL;
  return temp;
}
inline void Message::set_allocated_request(::pbmsg::Request* request) {
  delete request_;
  request_ = request;
  if (request) {
    set_has_request();
  } else {
    clear_has_request();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Message.request)
}

// optional .pbmsg.Respond respond = 5;
inline bool Message::has_respond() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_respond() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_respond() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_respond() {
  if (respond_ != NULL) respond_->::pbmsg::Respond::Clear();
  clear_has_respond();
}
inline const ::pbmsg::Respond& Message::respond() const {
  // @@protoc_insertion_point(field_get:pbmsg.Message.respond)
  return respond_ != NULL ? *respond_ : *default_instance_->respond_;
}
inline ::pbmsg::Respond* Message::mutable_respond() {
  set_has_respond();
  if (respond_ == NULL) {
    respond_ = new ::pbmsg::Respond;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Message.respond)
  return respond_;
}
inline ::pbmsg::Respond* Message::release_respond() {
  // @@protoc_insertion_point(field_release:pbmsg.Message.respond)
  clear_has_respond();
  ::pbmsg::Respond* temp = respond_;
  respond_ = NULL;
  return temp;
}
inline void Message::set_allocated_respond(::pbmsg::Respond* respond) {
  delete respond_;
  respond_ = respond;
  if (respond) {
    set_has_respond();
  } else {
    clear_has_respond();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Message.respond)
}

// optional .pbmsg.Notify notify = 6;
inline bool Message::has_notify() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Message::set_has_notify() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Message::clear_has_notify() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Message::clear_notify() {
  if (notify_ != NULL) notify_->::pbmsg::Notify::Clear();
  clear_has_notify();
}
inline const ::pbmsg::Notify& Message::notify() const {
  // @@protoc_insertion_point(field_get:pbmsg.Message.notify)
  return notify_ != NULL ? *notify_ : *default_instance_->notify_;
}
inline ::pbmsg::Notify* Message::mutable_notify() {
  set_has_notify();
  if (notify_ == NULL) {
    notify_ = new ::pbmsg::Notify;
  }
  // @@protoc_insertion_point(field_mutable:pbmsg.Message.notify)
  return notify_;
}
inline ::pbmsg::Notify* Message::release_notify() {
  // @@protoc_insertion_point(field_release:pbmsg.Message.notify)
  clear_has_notify();
  ::pbmsg::Notify* temp = notify_;
  notify_ = NULL;
  return temp;
}
inline void Message::set_allocated_notify(::pbmsg::Notify* notify) {
  delete notify_;
  notify_ = notify;
  if (notify) {
    set_has_notify();
  } else {
    clear_has_notify();
  }
  // @@protoc_insertion_point(field_set_allocated:pbmsg.Message.notify)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pbmsg

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pbmsg::MSG> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pbmsg::MSG>() {
  return ::pbmsg::MSG_descriptor();
}
template <> struct is_proto_enum< ::pbmsg::ERR_CODE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pbmsg::ERR_CODE>() {
  return ::pbmsg::ERR_CODE_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Message_2eproto__INCLUDED
